import { GoogleGenAI } from "@google/genai";
import { GenerationConfig } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Converts a File object to a Base64 string.
 */
export const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => {
            const result = reader.result as string;
            // Remove the Data URL prefix (e.g., "data:image/jpeg;base64,")
            const base64 = result.split(',')[1];
            resolve(base64);
        };
        reader.onerror = (error) => reject(error);
    });
};

/**
 * Generates an event visualization based on the uploaded image and configuration.
 */
export const generateEventVisualization = async (config: GenerationConfig): Promise<string> => {
    if (!config.image) throw new Error("No image provided");

    const base64Image = await fileToBase64(config.image);

    const prompt = `
        Act as a world-class event designer and 3D visualizer.
        
        Task: Transform the provided venue image into a realistic, fully decorated event setup.
        
        Event Type: ${config.eventType}
        Theme/Style: ${config.theme}
        Color Palette: ${config.colorPalette}
        Specific Requirements: ${config.additionalNotes}
        
        Guidelines:
        1. STRICTLY PRESERVE the architectural structure, perspective, walls, ceiling, and floor layout of the original image.
        2. Fill the space with appropriate furniture (tables, chairs, stages) based on the event type.
        3. Apply high-quality lighting, shadows, and reflections to make it look photorealistic.
        4. Add floral arrangements, drapes, centerpieces, and ambient lighting matching the theme.
        5. The output must look like a professional photograph of the actual event taking place in this specific room.
    `;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image', // Using 2.5 Flash Image for editing capabilities
            contents: {
                parts: [
                    {
                        inlineData: {
                            mimeType: config.image.type,
                            data: base64Image
                        }
                    },
                    {
                        text: prompt
                    }
                ]
            },
            config: {
                // No specific image config needed for 2.5-flash-image when doing edit/transform
                // It infers from the prompt and input image
            }
        });

        // Iterate through parts to find the image
        if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
            for (const part of response.candidates[0].content.parts) {
                if (part.inlineData && part.inlineData.data) {
                    return `data:image/png;base64,${part.inlineData.data}`;
                }
            }
        }

        throw new Error("No image generated by the model.");

    } catch (error) {
        console.error("Gemini API Error:", error);
        throw error;
    }
};
